version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shades-frontend
    restart: unless-stopped
    ports:
      - "5991:5991"
    environment:
      NODE_ENV: production 